<?php
## FILE GENERATED BY MAGRATHEA.
## This file was automatically generated and changes can be overwritten through the admin
## -- date of creation: [2024-04-16 03:59:10]

namespace Dunedin\Gag\Base;

use Magrathea2\MagratheaModelControl;

class GagControlBase extends MagratheaModelControl {
	protected static $modelNamespace = "Dunedin\Gag";
	protected static $modelName = "Gag";
	protected static $dbTable = "gags";
}
